title: Tristan_McCoy
email: tristanmccoy1@yahoo.com
description: >-
  Creative data professional.
linkedin_username: tristanmccoy
show_downloads: True
minimal_mistakes_skin: dirt
search: True

markdown: kramdown
remote_theme: mistakes/minimal-mistakes

author:
  name    : "Tristan McCoy"
  avatar  : "/assets/images/IMG_5631.jpeg"
  bio     : "Creative data professional"
  links: 
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/tristanmccoy/"
    
