title: Tristan_McCoy
email: tristanmccoy1@yahoo.com
linkedin_username: tristanmccoy
show_downloads: True
minimal_mistakes_skin: dirt
theme: jekyll-theme-minimal

author:
  name: "Tristan McCoy"
  avatar: "/assets/images/IMG_5631.jpeg"
  bio: "Creative data professional"
  links: 
    - label: "LinkedIn"
    icon: "fa-brands fa-linkedin"
    url: "https://www.linkedin.com/in/tristanmccoy/"
    
